"""all new tables

Revision ID: f45c54362920
Revises: 
Create Date: 2021-12-03 13:46:11.176790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45c54362920'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Calender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=True),
    sa.Column('day_begin', sa.DateTime(), nullable=True),
    sa.Column('day_end', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('dni', sa.String(length=12), nullable=True),
    sa.Column('status_teacher', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['status_teacher'], ['Status.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('user_type', sa.String(length=24), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_type'], ['UserType.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ClassSchedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher', sa.String(length=24), nullable=True),
    sa.Column('subject', sa.String(length=24), nullable=True),
    sa.Column('calender_sch', sa.String(length=24), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calender_sch'], ['Calender.name'], ),
    sa.ForeignKeyConstraint(['subject'], ['Subject.name'], ),
    sa.ForeignKeyConstraint(['teacher'], ['Teacher.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClassSchedule')
    op.drop_table('User')
    op.drop_table('Teacher')
    op.drop_table('UserType')
    op.drop_table('Subject')
    op.drop_table('Status')
    op.drop_table('Calender')
    # ### end Alembic commands ###
